### ISSUE TITLE
Broken link to "ROOT" in TL description of element <ead>

### ISSUE THREAD

**Issue by kerstarno** [SAA-SDT/EAS-TagLibraries#46]
## Creator of issue

1. Kerstin Arnold
2. here: team lead EAD team, TS-EAS
3. @kerstarno 
4.

## The issue relates to

- [ ] EAC-CPF schema issue
- [ ] EAC-CPF Tag Library issue
- [ ] EAD schema issue
- [x] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature

* Text: 

## Reporting a bug

* The description of the element `<ead>` in the tag library includes a link to "ROOT" under "May occur within" (https://www.loc.gov/ead/EAD3taglib/EAD3.html#elem-ROOT). As such element does not exist, the link does not resolve. Could this be changed into simple text?
* Furthermore, we could add a brief example, maybe:
```
<ead xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="http://ead3.archivists.org/schema/" audience="external" base="https://www.loc.gov/ead/">
    <control>
        [...]
    </control>
    <archdesc level="fonds">
        [...]
    </archdesc>
</ead>
```

## Suggested Solution

* Text: 

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

* Text: 

## Your Environment can be a clue to a bug

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):

**Comment by kerstarno** [comment]
@alexduryee - not sure, if this still could be included in the patch 1.1.1?

**Comment by fordmadox** [comment]
I think we can get it into the patch (so that folks won't be confused and think that there's an element in EAD named ROOT).  i *might* have time to update this this afternoon:  https://github.com/SAA-SDT/EAS-TagLibraries/blob/ad/generating_tls_for_ed99fd9/tei/EAD3-TL-eng.xml#L6519-L6521   @kerstarno I'm about to give the go-ahead for the schema.  aside from the two issues you noted, is there anything else needed for the tag libraries?   

i wanted to check with the print copy, but I don't have that one handy.  i do have a copy of the EAD 1.0 print tag library, though, and for ```<ead-grp>``` it says:  "Not applicable; highest-level element in EAD Group DTD".  but if we have any value there whatsoever, we'd need to make sure that text isn't turned into a link.

is the preferred solution to have some text that's not a link (like "Not applicable"; etc.) or to remove the "May occur within" section entirely from that context?

**Comment by kerstarno** [comment]
Hi @fordmadox - haven't had time to have a thorough look at the latest TL draft for the patch, I only came across the two issues I've mentioned while doing some checks as part of the shared schema work. Will try to have a closer look during the morning/midday (Europeana time) and will let you know via mail.

As for this issue here: I think, I'd go with the way it's done in the EAC-CPF tag library, which simply does not have the "May occur within:" for the root element.

**Comment by fordmadox** [comment]
FYI:  https://github.com/SAA-SDT/EAS-TagLibraries/commit/e93bafcf7cf5302cdf3c0666565203a3a23ba3aa
