### ISSUE TITLE
Typo in English summary of scriptcode

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/EAS-TagLibraries#50]
Typo in English summary of attribute `@scriptcode`

## Creator of issue
1. Silke Jagodzinski

## The issue relates to

- [ ] EAC-CPF schema issue
- [ ] EAC-CPF Tag Library issue
- [ ] EAD schema issue
- [x] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Reporting a bug

* Text: cf. https://www.loc.gov/ead/EAD3taglib/EAD3.html#attr-scriptcode

> Content should be taken from ISO 15924 Co**dse** for the Representation of Names of Scripts, [...]

**Comment by kerstarno** [comment]
@alexduryee - apologies for not having gotten around to reviewing the new EAD3 TL earlier and hence for not replying to this one previously. 

The current draft still says "Codse" instead of "Codes", which is strange, because I can see the change having been made here: https://github.com/SAA-SDT/EAS-TagLibraries/pull/72/files.

**Comment by alexduryee** [comment]
Fixed on development branch.

**Comment by kerstarno** [comment]
Closing this as it has been resolved.
