### ISSUE TITLE
Addition of "Examples" heading in the attributes description

### ISSUE THREAD

**Issue by karinbredenberg** [SAA-SDT/EAS-TagLibraries#63]
## Creator of issue

1. Karin Bredenberg, TS EAS co-chair

## The issue relates to

- [ ] EAC-CPF schema issue
- [ ] EAC-CPF Tag Library issue
- [ ] EAD schema issue
- [ ] EAD Tag Library issue
- [ ] Schema issue
- [x] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature

* Text: Addition of "Examples" heading in the attribute descriptions. Should work in the same way as examples in element descriptions. Means updates needed in TEI-schema, transformations and template.

**Comment by alexduryee** [comment]
It looks like the transformation process already supports this - there's an attribute example in the EAD3 TEI (https://github.com/SAA-SDT/EAS-TagLibraries/blob/master/tei/EAD3-TL-eng.xml#L401).  If we can get examples for all of the attributes, we can just slot them in, and it'll render in the PDF/HTML without issue.

**Comment by alexduryee** [comment]
As discussed at 2020-09-14 meeting:
- Review shared attributes between EAD/EAC-CPF revision to minimize overlapping work
- Review element examples for potentially extant attribute examples
- Identity EAD3-only attributes that will require examples
- Request examples for attributes that still require them from subteam(s)
- Deadline: next meeting (2020-10-20)

**Comment by kerstarno** [comment]
Shared attributes:

- actuate (is xlink:actuate in EAC-CPF at the moment, but XLink will be removed, so example could potentially be used in both EAS)
- arcrole (is xlink:arcole in EAC-CPF at the moment, but XLink will be removed, so example could potentially be used in both EAS)
- audience (currently not in EAC-CPF, but will be added in the new version)
- base (is xml:base in EAC-CPF at the moment; status of XML namespace still/again pending, but example could potentially be used in both EAS)
- calendar (currently not in EAC-CPF, but will be added in the new version)
- certainty (currently not in EAC-CPF, but will be added in the new version)
- coordinatesystem (currently not in EAC-CPF, but will be added in the new version)
- countrycode 
- countryencoding (currently not in EAC-CPF, but will be added in the new version)
- dateencoding (currently not in EAC-CPF, but will be added in the new version)
- era (currently not in EAC-CPF, but will be added in the new version)
- href (is xlink:href in EAC-CPF at the moment, but XLink will be removed, so example could potentially be used in both EAS)
- id (is xml:id in EAC-CPF at the moment; status of XML namespace still/again pending, but example could potentially be used in both EAS)
- lang (is xml:lang in EAC-CPF at the moment; status of XML namespace still/again pending, but example could potentially be used in both EAS)
- langcode (is languageCode in EAC-CPF at the moment, but naming will be aligned in a future version of EAD, so example could potentially be used in both EAS)
- langencoding (currently not in EAC-CPF, but will be added in the new version - as languageEncoding) 
- lastdatetimeverified 
- linkrole (is xlink:role in EAC-CPF at the moment, but XLink will be removed, so example could potentially be used in both EAS)
- linktitle (is xlink:title in EAC-CPF at the moment, but XLink will be removed, so example could potentially be used in both EAS)
- localtype
- notafter
- notbefore
- repositoryencoding (currently not in EAC-CPF, but will be added in the new version) 
- scriptcode
- scriptencoding (currently not in EAC-CPF, but will be added in the new version) 
- show (is xlink:show in EAC-CPF at the moment, but XLink will be removed, so example could potentially be used in both EAS)
- source (is the equivalent to EAC-CPF's vocabularySource, so example could potentially be used in both EAS)
- standarddate
- standarddatetime
- transliteration (though this is likely to be removed in the next version of EAC-CPF and hence in the next version of EAD)

EAD only attributes:
- abbr 
- align 
- althead 
- altrender 
- approximate 
- char 
- charoff 
- colname 
- colnum 
- cols 
- colsep 
- colwidth 
- containerid 
- coverage 
- daotype 
- datechar 
- dsctype 
- encodinganalog 
- entityref 
- expan 
- frame 
- identifier 
- instanceurl 
- label 
- level 
- listtype 
- mark 
- morerows 
- nameend 
- namest 
- normal 
- numeration 
- otherdaotype 
- otherdsctype 
- otherlevel 
- otherphysdescstructuredtype 
- otherrelationtype 
- parallel 
- parent 
- pgwide 
- physdescstructuredtype 
- relatedencoding 
- relationtype 
- relator 
- render 
- repositorycode 
- rowsep 
- rules 
- script 
- target 
- unit 
- unitdatetype 
- valign 
- value 
- xpointer

**Comment by kerstarno** [comment]
I'll have a look through the TL in terms of which of these might already be covered via elements used for the elements that they go with in a next step.

**Comment by kerstarno** [comment]
### Shared attributes:

- actuate (is xlink:actuate in EAC-CPF at the moment, but XLink will be removed, so example could potentially be used in both EAS)
  - Could use the last example in EAD3 TL for `<conventionDeclaration><citation>` (https://www.loc.gov/ead/EAD3taglib/EAD3.html#elem-conventiondeclaration) and/or the first example in EAD3 TL for `<daoset>` (https://www.loc.gov/ead/EAD3taglib/EAD3.html#elem-daoset)
- arcrole (is xlink:arcole in EAC-CPF at the moment, but XLink will be removed, so example could potentially be used in both EAS)
  - already has an example
  - alternatively - or additionally - the third example in EAD3 TL for `<relations>` could be used (https://www.loc.gov/ead/EAD3taglib/EAD3.html#elem-relations)
  - EAC-CPF TL has one example in the introduction paragraph on "Integrating XLink into EAC-CPF", sub-paragraph "Link Behavior Attributes"
- audience (currently not in EAC-CPF, but will be added in the new version)
  - Could use the last example in EAD3 TL for `<titleproper>` (https://www.loc.gov/ead/EAD3taglib/EAD3.html#elem-titleproper)
- base (is xml:base in EAC-CPF at the moment; status of XML namespace still/again pending, but example could potentially be used in both EAS)
  - No examples in TL (neither EAD3, nor EAC-CPF) -> **Needs example**
- calendar (currently not in EAC-CPF, but will be added in the new version)
  - One example in EAD3 TL (used in various places, e.g. for `<archdesc>`, https://www.loc.gov/ead/EAD3taglib/EAD3.html#elem-archdesc)
  - **Could benefit from additional example** that is not using the "gregorian" calendar
- certainty (currently not in EAC-CPF, but will be added in the new version)
  - One example in EAD3 TL (used in various places, e.g. third example for `<unitdatestructured>`, https://www.loc.gov/ead/EAD3taglib/EAD3.html#elem-unitdatestructured)
  - However, we would probably want to use examples that include the values from EDTF that we'd want to recommend for use with `@certainty` following the dates topic paper as discussed in the EAC team, i.e. "uncertain", "approximate" and "uncertain and approximate" (see also https://github.com/SAA-SDT/TS-EAS-subteam-notes/blob/master/eaccpf-subteam/working-documents/topics/dates/Topic_dates_20200911.pdf)
  - **Could benefit from additional example**
- coordinatesystem (currently not in EAC-CPF, but will be added in the new version)
  - Could use examples in EAD3 TL for `<geographiccoordinates>`(https://www.loc.gov/ead/EAD3taglib/EAD3.html#elem-geographiccoordinates), which includes three variations
- countrycode 
  - Could use first example in EAC-CPF TL for `<placeEntry>` (https://eac.staatsbibliothek-berlin.de/schema/taglibrary/cpfTagLibrary2019_EN.html#elem-placeEntry), the `<unitid>` part of the first example in EAD3 TL for `<abstract>`(https://www.loc.gov/ead/EAD3taglib/EAD3.html#elem-abstract), and/or the `<maintenanceagency>` part of the first and/or second example in EAD3 TL for `<control>` (https://www.loc.gov/ead/EAD3taglib/EAD3.html#elem-control)
- countryencoding (currently not in EAC-CPF, but will be added in the new version)
  - Could use one of the examples in EAD3 TL for `<control>` (https://www.loc.gov/ead/EAD3taglib/EAD3.html#elem-control)
  - **Could benefit from additional example** that is not using the standard option "iso3166-1"
- dateencoding (currently not in EAC-CPF, but will be added in the new version)
  - Could use one of the examples in EAD3 TL for `<control>` (https://www.loc.gov/ead/EAD3taglib/EAD3.html#elem-control)
  - **Could benefit from additional example** that is not using the standard option "iso8601"
- era (currently not in EAC-CPF, but will be added in the new version)
  - One example in EAD3 TL (used in various places, e.g. for `<archdesc>`, https://www.loc.gov/ead/EAD3taglib/EAD3.html#elem-archdesc)
  - **Could benefit from additional example** that is not using the "common era"
- href (is xlink:href in EAC-CPF at the moment, but XLink will be removed, so example could potentially be used in both EAS)
  - Could use the last example in EAD3 TL for `<conventionDeclaration><citation>` (https://www.loc.gov/ead/EAD3taglib/EAD3.html#elem-conventiondeclaration)
  - Could additionally use the example in EAC-CPF TL for `<cpfRelation>` (https://eac.staatsbibliothek-berlin.de/schema/taglibrary/cpfTagLibrary2019_EN.html#elem-cpfRelation), which shows an relative link as value for `@xlink:href`
  - Could also use the example in EAC-CPF TL for `<rightsDeclaration>` (https://eac.staatsbibliothek-berlin.de/schema/taglibrary/cpfTagLibrary2019_EN.html#elem-rightsDeclaration)
- id (is xml:id in EAC-CPF at the moment; status of XML namespace still/again pending, but example could potentially be used in both EAS)
  - The only two instances of "id" in EAC-CPF TL actually use `@id` instead of `@xml:id` (see last examples for `<relationEntry>, https://eac.staatsbibliothek-berlin.de/schema/taglibrary/cpfTagLibrary2019_EN.html#elem-relationEntry, and for `<resourceRelation>` (https://eac.staatsbibliothek-berlin.de/schema/taglibrary/cpfTagLibrary2019_EN.html#elem-resourceRelation), so should not be used any more
  - EAD3 TL does include some examples, including one that also shows a `@parent` attribute that refers to the`@id` in question (see second example for `<container>`, https://www.loc.gov/ead/EAD3taglib/EAD3.html#elem-container), but as there also is `@containerid` in EAD3, we might rather want to use an example from another context
  - **Could definitely benefit from additional example** 
- lang (is xml:lang in EAC-CPF at the moment; status of XML namespace still/again pending, but example could potentially be used in both EAS)
  - Could use the first example in EAC-CPF TL for `<nameEntryParallel>` (https://eac.staatsbibliothek-berlin.de/schema/taglibrary/cpfTagLibrary2019_EN.html#elem-nameEntryParallel)
  - Could also use  the EAD3 TL example for `<corpname>` (https://www.loc.gov/ead/EAD3taglib/EAD3.html#elem-corpname)
- langcode (is languageCode in EAC-CPF at the moment, but naming will be aligned in a future version of EAD, so example could potentially be used in both EAS)
  - Could use the first and/or third example in EAD3 TL for `<langmaterial>` (https://www.loc.gov/ead/EAD3taglib/EAD3.html#elem-langmaterial)
  - Could also use the examples in EAC-CPF TL for `<languageDeclaration>` (https://eac.staatsbibliothek-berlin.de/schema/taglibrary/cpfTagLibrary2019_EN.html#elem-languageDeclaration) or `<languageUsed>` (https://eac.staatsbibliothek-berlin.de/schema/taglibrary/cpfTagLibrary2019_EN.html#elem-languageUsed)
- langencoding (currently not in EAC-CPF, but will be added in the new version - as languageEncoding) 
  - Could use one of the examples in EAD3 TL for `<control>` (https://www.loc.gov/ead/EAD3taglib/EAD3.html#elem-control)
  - **Could benefit from additional example** that is not using the standard option "iso639-2b"
- lastdatetimeverified 
  - Could use the last example in EAD3 TL for `<conventionDeclaration><citation>` (https://www.loc.gov/ead/EAD3taglib/EAD3.html#elem-conventiondeclaration)
  - Could also use the `<mandate>` example in EAC-CPF TL given for `<term>` (https://eac.staatsbibliothek-berlin.de/schema/taglibrary/cpfTagLibrary2019_EN.html#elem-term)
- linkrole (is xlink:role in EAC-CPF at the moment, but XLink will be removed, so example could potentially be used in both EAS)
  - Already has an example
  - Could additionally use the example in EAD3 TL for `<ref>`(https://www.loc.gov/ead/EAD3taglib/EAD3.html#elem-ref)
  - Could also use the first, third, and fourth examples in EAD3 TL for `<relations>` (https://www.loc.gov/ead/EAD3taglib/EAD3.html#elem-relations)
  - Similar to the last ones, EAC-CPF TL includes an example as part of the introduction paragraph on "Integrating XLink into EAC-CPF", sub-paragraph "Link Behavior Attributes"
- linktitle (is xlink:title in EAC-CPF at the moment, but XLink will be removed, so example could potentially be used in both EAS)
  - Could use the last example in EAD3 TL for `<conventionDeclaration><citation>` (https://www.loc.gov/ead/EAD3taglib/EAD3.html#elem-conventiondeclaration)
  - Could also use the last example in EAD3 TL for `<source>` (https://www.loc.gov/ead/EAD3taglib/EAD3.html#elem-source)
- localtype
  - Could use the example in EAC-CPF TL for `<address>` (https://eac.staatsbibliothek-berlin.de/schema/taglibrary/cpfTagLibrary2019_EN.html#elem-address)
  - Could also use the first example in EAD3 TL for `<container>` (https://www.loc.gov/ead/EAD3taglib/EAD3.html#elem-container)
  - Could also use the second example in EAD3 TL for `<dao>` (https://www.loc.gov/ead/EAD3taglib/EAD3.html#elem-dao)
- notafter
  - Could use the last example in EAD3 TL for `<daterange>` (https://www.loc.gov/ead/EAD3taglib/EAD3.html#elem-daterange)
- notbefore
  - Could use the last example in EAD3 TL for `<daterange>` (https://www.loc.gov/ead/EAD3taglib/EAD3.html#elem-daterange)
- repositoryencoding (currently not in EAC-CPF, but will be added in the new version) 
  - Could use one of the examples in EAD3 TL for `<control>` (https://www.loc.gov/ead/EAD3taglib/EAD3.html#elem-control)
  - **Could benefit from additional example** that is not using the standard option "iso15511"
- scriptcode
  - Could use the first and/or third example in EAD3 TL for `<langmaterial>` (https://www.loc.gov/ead/EAD3taglib/EAD3.html#elem-langmaterial)
  - Could also use the examples in EAC-CPF TL for `<languageDeclaration>` (https://eac.staatsbibliothek-berlin.de/schema/taglibrary/cpfTagLibrary2019_EN.html#elem-languageDeclaration) or `<languageUsed>` (https://eac.staatsbibliothek-berlin.de/schema/taglibrary/cpfTagLibrary2019_EN.html#elem-languageUsed)
- scriptencoding (currently not in EAC-CPF, but will be added in the new version) 
  - Could use one of the examples in EAD3 TL for `<control>` (https://www.loc.gov/ead/EAD3taglib/EAD3.html#elem-control)
  - **Could benefit from additional example** that is not using the standard option "iso15924"
- show (is xlink:show in EAC-CPF at the moment, but XLink will be removed, so example could potentially be used in both EAS)
  - Could use the last example in EAD3 TL for `<conventionDeclaration><citation>` (https://www.loc.gov/ead/EAD3taglib/EAD3.html#elem-conventiondeclaration) and/or the first example in EAD3 TL for `<daoset>` (https://www.loc.gov/ead/EAD3taglib/EAD3.html#elem-daoset)
- source (is the equivalent to EAC-CPF's vocabularySource, so example could potentially be used in both EAS)
  - Could use the example in EAD3 TL for `<function>` (https://www.loc.gov/ead/EAD3taglib/EAD3.html#elem-function)
  - Could also use the `<function>` example in EAC-CPF TL given for `<term>` (https://eac.staatsbibliothek-berlin.de/schema/taglibrary/cpfTagLibrary2019_EN.html#elem-term)
- standarddate
  - Could use the first example in EAD3 TL for `<fromdate>` (https://www.loc.gov/ead/EAD3taglib/EAD3.html#elem-fromdate)
  - Could also use the two examples in EAC-CPF TL for `<date>` (https://eac.staatsbibliothek-berlin.de/schema/taglibrary/cpfTagLibrary2019_EN.html#elem-date)
- standarddatetime
  - Could use the first example in EAC-CPF TL for `<eventDateTime>` (https://eac.staatsbibliothek-berlin.de/schema/taglibrary/cpfTagLibrary2019_EN.html#elem-eventDateTime)
  - Could also use the examples in EAD3 TL for `<eventdatetime>` (https://www.loc.gov/ead/EAD3taglib/EAD3.html#elem-eventdatetime)
- transliteration (though this is likely to be removed in the next version of EAC-CPF and hence in the next version of EAD)
  - Could use the example in EAC-CPF TL for `<multipleIdentities>` (https://eac.staatsbibliothek-berlin.de/schema/taglibrary/cpfTagLibrary2019_EN.html#elem-multipleIdentities)
  - ** Could benefit from additional example**

**Comment by kerstarno** [comment]
### EAD-only attributes
- abbr 
  - Could use the two examples in EAD3 TL for `<expan>` (https://www.loc.gov/ead/EAD3taglib/EAD3.html#elem-expan)
- align 
  - Could use the example in EAD3 TL for `<row>` (https://www.loc.gov/ead/EAD3taglib/EAD3.html#row)
  - Could also use the example in EAD3 TL for `<table>` (https://www.loc.gov/ead/EAD3taglib/EAD3.html#table)
- althead 
  - No examples in TL (neither EAD3, nor EAD 2002) -> **Needs example**
- altrender
  - Could use last example in EAD3 TL for `<titleproper>` (https://www.loc.gov/ead/EAD3taglib/EAD3.html#titleproper)
- approximate 
  - No examples in TL (neither EAD3, nor EAD 2002) -> **Needs example**
- char 
  - No actual examples in TL (neither EAD3, nor EAD 2002), only descriptive example e.g. as part of the description of `<entry>` in EAD 2002 TL (https://www.loc.gov/ead/tglib/elements/entry.html) -> **Needs example**
- charoff 
  - No examples in TL (neither EAD3, nor EAD 2002) -> **Needs example**
- colname 
  - Could use the example in EAD3 TL for `<row>` (https://www.loc.gov/ead/EAD3taglib/EAD3.html#row)
  - **Could maybe benefit from additional example**
- colnum 
  - Could use the example in EAD3 TL for `<row>` (https://www.loc.gov/ead/EAD3taglib/EAD3.html#row)
- cols 
  - Could use the example in EAD3 TL for `<row>` (https://www.loc.gov/ead/EAD3taglib/EAD3.html#row)  
  -  Could also use the example in EAD3 TL for `<table>` (https://www.loc.gov/ead/EAD3taglib/EAD3.html#table)
- colsep 
  - Could use the example in EAD3 TL for `<row>` (https://www.loc.gov/ead/EAD3taglib/EAD3.html#row)
- colwidth 
  -  Could use the example in EAD3 TL for `<table>` (https://www.loc.gov/ead/EAD3taglib/EAD3.html#table)
- containerid 
  - No examples in TL (neither EAD3, nor EAD 2002) -> **Needs example**, ideally one that illustrates the difference between `@containerid` and `@(xml:)id` 
- coverage 
  -  Could use the examples in EAD3 TL for `<daoset>` (https://www.loc.gov/ead/EAD3taglib/EAD3.html#daoset)
  -  Could also use some examples from EAD3 TL for `<physdescstructured>` (https://www.loc.gov/ead/EAD3taglib/EAD3.html#physdescstructured)
- daotype 
  - Could use the examples in EAD3 TL for `<dao>` (https://www.loc.gov/ead/EAD3taglib/EAD3.html#dao)
  - **Could benefit from additional example** that is not using the option "derived"
- datechar
  - No examples in TL (neither EAD3, nor EAD 2002) -> **Needs example**
- dsctype 
  - Could use the examples in EAD3 TL for `<dsc>` (https://www.loc.gov/ead/EAD3taglib/EAD3.html#dsc)
- encodinganalog 
  - Alreday has an example
  - Could additionally use the example in EAD3 TL for `<archdesc>` (https://www.loc.gov/ead/EAD3taglib/EAD3.html#archdesc)
- entityref 
  - Only one example in EAD3 TL, which might not be ideal (see `<lb>`, https://www.loc.gov/ead/EAD3taglib/EAD3.html#lb)
  - Could adapt the examples in EAD 2002 TL for `<extptr>` (https://www.loc.gov/ead/tglib/elements/extptr.html) and `<extref>` (https://www.loc.gov/ead/tglib/elements/extref.html) to `<ref>` with `@entityref`
- expan 
  - Could use the examples in EAD3 TL for `<abbr>` (https://www.loc.gov/ead/EAD3taglib/EAD3.html#abbr) which mirror the examples for `@abbr`
  - Could also use the example in EAD 2002 TL for `<abbr>` (https://www.loc.gov/ead/tglib/elements/abbr.html)
- frame 
  - Could use the example in EAD3 TL for `<row>` (https://www.loc.gov/ead/EAD3taglib/EAD3.html#row)
  - Could also use the example in EAD3 TL for `<table>` (https://www.loc.gov/ead/EAD3taglib/EAD3.html#table)
- identifier 
  - Could use the examples in EAD3 TL for `<corpname>` (https://www.loc.gov/ead/EAD3taglib/EAD3.html#corpname)
  - Could also use the fourth example in EAD3 TL for `<physdescstructured>` (https://www.loc.gov/ead/EAD3taglib/EAD3.html#physdescstructured)
  - Could also use the second example in EAD3 TL for `<unitid>` (https://www.loc.gov/ead/EAD3taglib/EAD3.html#unitid) showing the different use in this context
- instanceurl 
  - Could use the second example in EAD3 TL for `<control>` (https://www.loc.gov/ead/EAD3taglib/EAD3.html#control)
  - Could also use second example in EAD3 TL for `<otherrecordid>` (https://www.loc.gov/ead/EAD3taglib/EAD3.html#otherrecordid)
- label 
  - Could use the examples in EAD3 TL for `<abstract>` (https://www.loc.gov/ead/EAD3taglib/EAD3.html#abstract)
  - **Would be great to have an additional example** for labels in another language than English maybe
- level 
  - Could use the example in EAD3 TL for `<c>` (https://www.loc.gov/ead/EAD3taglib/EAD3.html#c)
- listtype 
  - Could use the examples in EAD3 TL for `<list>` (https://www.loc.gov/ead/EAD3taglib/EAD3.html#list)
- mark 
  - Could use the first example in EAD3 TL for `<list>` (https://www.loc.gov/ead/EAD3taglib/EAD3.html#list)
- morerows
  - No examples in TL (neither EAD3, nor EAD 2002) -> **Needs example**
- nameend 
  - No examples in TL (neither EAD3, nor EAD 2002) -> **Needs example**
- namest 
  - No examples in TL (neither EAD3, nor EAD 2002) -> **Needs example**
- normal 
  - Could use the last example in EAD3 TL for `<unitdate>` (https://www.loc.gov/ead/EAD3taglib/EAD3.html#unitdate) for more complex ISO8601 encoding
  - Could also use the first example in EAD3 TL for `<publisher>` (https://www.loc.gov/ead/EAD3taglib/EAD3.html#publisher) for more complex ISO8601 encoding (although should stick with the one using a date range)
  - Could also use the last example in EAD3 TL for `<acqinfo>` (https://www.loc.gov/ead/EAD3taglib/EAD3.html#acqinfo) for simple ISO8601 encoding (although this only is a single date and might hence be too close to `@standarddate`)
  - Could use the `<descriptivenote>` part of the example in EAD3 TL for `<objectxmlwrap>` (https://www.loc.gov/ead/EAD3taglib/EAD3.html#objectxmlwrap) for `@normal` with controlled access terms
- numeration 
  - Could use one of the examples in EAD3 TL for `<fileplan>`(https://www.loc.gov/ead/EAD3taglib/EAD3.html#fileplan)
  - Could also use the last example in EAD3 TL for `<list>`(https://www.loc.gov/ead/EAD3taglib/EAD3.html#list)
- otherdaotype 
  - No examples in TL (neither EAD3, nor EAD 2002) -> **Needs example**
- otherdsctype 
  - No examples in TL (neither EAD3, nor EAD 2002) -> **Needs example**
- otherlevel 
  - Could use the example in EAD 2002 TL for `<odd>` (https://www.loc.gov/ead/tglib/elements/odd.html)
  - Could also use the second example in EAD 2002 TL for `<repository>` (https://www.loc.gov/ead/tglib/elements/repository.html)
- otherphysdescstructuredtype 
  - Could use the last example in EAD3 TL for `<physdescstructured>` (https://www.loc.gov/ead/EAD3taglib/EAD3.html#elem-physdescstructured)
  - **Could benefit from additional example**
- otherrelationtype 
  - Could use the last example in EAD3 TL for `<relations>` (https://www.loc.gov/ead/EAD3taglib/EAD3.html#elem-relations)
  - **Could benefit from additional example**
- parallel 
  - Could use the first two examples in EAD3 TL for `<physdescset>` (https://www.loc.gov/ead/EAD3taglib/EAD3.html#elem-physdescset)
- parent 
  - Could use the second example in EAD3 TL for `<container>` (https://www.loc.gov/ead/EAD3taglib/EAD3.html#elem-container)
- pgwide 
  - No examples in TL (neither EAD3, nor EAD 2002) -> **Needs example**
- physdescstructuredtype 
  - Could use some of the examples in EAD3 TL for `<physdescstructured>` (https://www.loc.gov/ead/EAD3taglib/EAD3.html#elem-physdescstructured)
- relatedencoding 
  - Could use the example in EAD3 TL for `<archdesc>` (https://www.loc.gov/ead/EAD3taglib/EAD3.html#archdesc)
  - Could additionally use the first example in EAD3 TL for `<control>` (https://www.loc.gov/ead/EAD3taglib/EAD3.html#control)
- relationtype 
  - Could use examples in EAD3 TL for `<relations>` (https://www.loc.gov/ead/EAD3taglib/EAD3.html#elem-relations)
- relator 
  - Could use the first example in EAD3 TL for `<date>` (https://www.loc.gov/ead/EAD3taglib/EAD3.html#elem-date)
  - Could also use the first example in EAD3 TL for `<famname>` (https://www.loc.gov/ead/EAD3taglib/EAD3.html#elem-famname)
  - Could also use the second example in EAD3 TL for `<num>` (https://www.loc.gov/ead/EAD3taglib/EAD3.html#elem-num)
- render 
  - Could use the example in EAD3 TL for `<bibliography>` (https://www.loc.gov/ead/EAD3taglib/EAD3.html#elem-bibliography)
  - Could use the first example in EAD3 TL for `<appraisal>` (https://www.loc.gov/ead/EAD3taglib/EAD3.html#elem-appraisal)
- repositorycode 
  - Could use the second example in EAD3 TL for `<unitid>` (https://www.loc.gov/ead/EAD3taglib/EAD3.html#elem-unitid)
  - **Could benefit from additional example** e.g. one using an ISO15511 compliant (or an ISIL) code
- rowsep  
  - Could use the example in EAD3 TL for `<row>` (https://www.loc.gov/ead/EAD3taglib/EAD3.html#row)
- rules 
  - Could use the first example in EAD3 TL for `<abstract>` (https://www.loc.gov/ead/EAD3taglib/EAD3.html#abstract)
  - Could also use the first two examples in EAD3 TL for `<part>` (https://www.loc.gov/ead/EAD3taglib/EAD3.html#part)
- script 
  - Could use the example in EAD3 TL for `<archdesc>` (https://www.loc.gov/ead/EAD3taglib/EAD3.html#archdesc)
  - Could also use the second example in the EAD3 TL for `<foreign>` (https://www.loc.gov/ead/EAD3taglib/EAD3.html#foreign)
- target 
  - Could use the last example in EAD3 TL for `<famname>` (https://www.loc.gov/ead/EAD3taglib/EAD3.html#famname)
  - Could also use the example in EAD3 TL for `<indexentry>` (https://www.loc.gov/ead/EAD3taglib/EAD3.html#indexentry)
  - **Would be great to have an additional example** that also shows the `@(xml:)id` that is the target referred to
- unit 
  - Could use the last example in EAD3 TL for `<dimensions>` (https://www.loc.gov/ead/EAD3taglib/EAD3.html#dimensions)
  - **Could benefit from additional example**
- unitdatetype 
  - Could use the first two examples in EAD3 TL for `<unitdate>` (https://www.loc.gov/ead/EAD3taglib/EAD3.html#unitdate)
- valign 
  - Could use the example in EAD3 TL for `<row>` (https://www.loc.gov/ead/EAD3taglib/EAD3.html#row)
  - **Could benefit from additional example** using a different option than "middle"
- xpointer
  - No examples in TL (neither EAD3, nor EAD 2002) -> **Needs example**

**Comment by alexduryee** [comment]
Thank you!  I've added in examples for all but the following attributes:

- althead
- approximate
- base
- character
- charoff
- entityref
- morerows
- nameend
- namestart
- otherdaotype
- otherdsctype
- otherlevel
- pgwide
- transliteration
- xpointer

I generated a few that were not present in the TL already from an ArchivesSpace export (e.g. `id` vs. `containerid`, `datechar`) and copied up ones from the examples @kerstarno provided.

**Comment by kerstarno** [comment]
Further examples for the remaining attributes with the exception of `@entityref`.

For `@approximate`, `@base` and `@otherdaotype`
```
<archdesc level="collection">
  <did>
    <unittitle>AIDS Legal Referral Panel Records (see more at <ref 
    href="https://calisphere.org/collections/469/">Calisphere</ref>)</unittitle>
    <daoset base="https://calisphere.org/item/">
      <dao daotype="otherdaotype" otherdaotype="surrogate" href="d3888b77-7d95-4fd0-bcdd-ab5551a4f013"/>
      <dao daotype="otherdaotype" otherdaotype="surrogate" href="d5e032bf-57a3-45e9-9f14-1782bc2e95e7"/>
      <dao daotype="otherdaotype" otherdaotype="surrogate" href="fd76d8fb-cafb-44c5-a5b5-e34673498b7a"/>
    </daoset>
    <physdescstructured physdescstructuredtype="carrier" coverage="whole">
      <quantity approximate="true">15</quantity>
      <unittype>boxes</unittype>
    </physdescstructured>
  </did>
</archdesc>
```
For `@nameend`, `@namest`, and `@pgwide`
```
<scopecontent>
  <table pgwide="false">
    <tgroup cols="4">
      <colspec colnum="1" colname="correspondent"/>
      <colspec colnum="2" colname="total"/>
      <colspec colnum="3" colname="sent"/>
      <colspec colnum="4" colname="received"/>
      <thead>
        <row>
          <entry colname="correspondent">Correspondent</entry>
          <entry colname="total">Total number of letters</entry>
          <entry namest="sent" nameend="received">Letters sent and received</entry>
        </row>
      </thead>
      <tbody>
        <!-- [...] -->
        <row>
          <entry colname="correspondent">Douglass, Frederick</entry>
          <entry colname="total">93</entry>
          <entry colname="sent">47</entry>
          <entry colname="received">46</entry>
        </row>
        <row>
          <entry colname="correspondent">Phillips, Wendell</entry>
          <entry colname="total">17</entry>
          <entry colname="sent">12</entry>
          <entry colname="received">5</entry>
        </row>
        <!-- [...] -->
       </tbody>
     </tgroup>
   </table>
</scopecontent>
```
For `@althead`, `@char`, `@charoff`, `@morerows`, and `@pgwide`
```
<bioghist>
  <head althead="Family relations">Bach family relations listing spouses and children of the major family members</head>
  <table pgwide="true">
    <tgroup cols="3">
      <colspec colnum="1" colname="member"/>
      <colspec colnum="2" colname="spouse"/>
      <colspec colnum="3" colname="child" align="char" char="*" charoff="2"/>
      <thead>
        <row>
          <entry colname="member">Major family members</entry>
          <entry colname="spouse">Spouses</entry>
          <entry colname="child">Children</entry>
        </row>
      </thead>
      <tbody>
        <!-- [...] -->
        <row>
          <entry colname="member" morerows="5" valign="top">Johann Sebastian Bach (1685-1750)</entry>
          <entry colname="spouse" morerows="2" valign="top">Maria Barbara Bach (1684-1720)</entry>
          <entry colname="child">* Wilhelm Friedemann Bach (1710–1784)</entry>
        </row>
        <row>
          <entry colname="member"/>
          <entry colname="spouse"/>
          <entry colname="child">* Carl Philipp Emanuel Bach (1714–1788)</entry>
        </row>
        <row>
          <entry colname="member"/>
          <entry colname="spouse"/>
          <entry colname="child">* Johann Gottfried Bernhard Bach (1715–1739)</entry>
        </row>
        <row>
          <entry colname="member"/>
          <entry colname="spouse" morerows="2" valign="top">Anna Magdalena, geb. Wilcke (1701–1760)</entry>
          <entry colname="child">* Gottfried Heinrich Bach (1724–1763)</entry>
        </row>
        <row>
          <entry colname="member"/>
          <entry colname="spouse"/>
          <entry colname="child">* Johann Christoph Friedrich Bach (1732–1795)</entry>
        </row>
        <row>
          <entry colname="member"/>
          <entry colname="spouse"/>
          <entry colname="child">* Johann Christian Bach (1735–1782)</entry>
        </row>
        <!-- [...] -->
      </tbody>
    </tgroup>
  </table>
</bioghist>
```
 For `@xpointer` 
```
<relatedmaterial>
  <p>See the <ref xpointer="ScMG108.xml#letters">letters from Frederick Douglass, 1870-1886</ref></p>
</relatedmaterial>
```
For `@transliteration`
```
<relations>
  <relation relationtype="cpfrelation">
    <relationentry localtype="original-language" lang="ger">Hannah Arendt (1906-1975)</relationentry>
    <relationentry localtype="translation" lang="jap" transliteration="DIN32708">アーレント, ハナ (1906-1975)</relationentry>
  </relation>
</relations>
```
For `@otherdsctype` and `@otherlevel`
```
<dsc dsctype="otherdsctype" otherdsctype="structural">
  <c level="subseries">
    <did>
      <unittitle>Clippings</unittitle>
    </did>
    <c level="otherlevel" otherlevel="sub-subseries">
      <did>
        <unittitle>Clippings (chronological)</unittitle>
      </did>
    </c>
    <c level="otherlevel" otherlevel="sub-subseries">
      <did>
        <unittitle>Clippings (persons)</unittitle>
      </did>
    </c>
  </c>
  <c level="subseries">
    <did>
      <unittitle>Notes</unittitle>
    </did>
  </c>
</dsc>
<dsc dsctype="in-depth">
  <!-- [...] -->
  <c level="otherlevel" otherlevel="sub-subseries">
    <did>
      <unitid>1 to 159</unitid>
      <unittitle>Clippings (chronological)</unittitle>
      <unitdatestructured>
        <daterange>
          <fromdate standarddate="1952-06-12">12 June 1952</fromdate>
          <todate standarddate="1966">1966</todate>
        </daterange>
      </unitdatestructured>
      <abstract>This series consists of newspaper clippings gathered by Fred Reed, pertaining to the Champlain Transportation 
      Company, its vessels, and the vessels' crew members. Several of the folders of chronological clippings include subjects, 
      such as the move of the Ticonderoga (1954-1955) and the sale of the Champlain Transportation Company (1966).
      </abstract>
      <physdescstructured physdescstructuredtype="spaceoccupied" coverage="whole">
        <quantity>0.2</quantity>
        <unittype>meters</unittype>
      </physdescstructured>
      <!-- [...] -->
    </did>
  </c>
  <!-- [...] -->
</dsc>
```

**Comment by kerstarno** [comment]
Closing this issue as it has been resolved.
