### ISSUE TITLE
The transformation of <a> or <ref>?

### ISSUE THREAD

**Issue by karinbredenberg** [SAA-SDT/EAS-TagLibraries#64]
## Creator of issue

1. Karin Bredenberg, TS eAS co.chair

## The issue relates to

- [ ] EAC-CPF schema issue
- [ ] EAC-CPF Tag Library issue
- [ ] EAD schema issue
- [ ] EAD Tag Library issue
- [ ] Schema issue
- [x] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature

* Text: There are links to webpages that doesn't become links, make guidance on how to write links to become real links out on the internet.

**Comment by alexduryee** [comment]
Current practice: using `ref target=....' (e.g. https://github.com/SAA-SDT/EAS-TagLibraries/blob/master/tei/EAD3-TL-eng.xml#L32-L33).  This works fine in the HTML version of the TL, but the PDF XSLT just makes it blue text (ref. https://github.com/SAA-SDT/EAS-TagLibraries/blob/master/transformations/Taglibrary2pdf.xsl#L1403-L14)

TODO: in addition to creating a link example in the template TEI, update the PDF XSLT to generate actionable links instead of blue text.

**Comment by alexduryee** [comment]
Fixed and merged.
